### ISSUE TITLE
Implement periodic i2b2 services restart to work around freeze

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/ncats-act#3]
i2b2 will get slower and slower responding to queries over a period of weeks to months, and ultimately it will stop responding altogether. The culprit seems to be a hung JBoss server. The last time this happened, and the time before, there was nothing in the JBoss logs indicating a problem. Not sure what the issue is, and I don't see any acknowledgement of a specific i2b2 or JBoss issue. In the meantime, we should implement a cronjob that restarts JBoss periodically, like once a week at a time where we would expect few if any users.

**Comment by akalsan** [comment]
i have a cron job on the QA and Prod i2b2srvs machines to restart jboss every monday at 7:30 a.m. I figured even if something goes wrong during the restart, the downtime is less compared to restarting in the middle of the night or on the weekend. 
I tested the script with a daily cron job and it restarted jboss and i am able to log in to i2b2 and run queries. If you want to take a look -  The script is in /etc/cron.weekly and the timing and schedule is in /etc/crontab file.

**Comment by akalsan** [comment]
set it up for 3:30 a.m monday morning.

**Comment by arpost** [comment]
Please document what you did here so we can recreate it if necessary.

**Comment by akalsan** [comment]
A file restart-jboss.sh is created in /etc/cron.weekly folder. The contents of this file is the two lines below. 

#!/bin/bash
/etc/init.d/jboss restart

In etc/crontab file copy the below line to schedule executing the restart script at 3:30a.m on every monday. 
30 3 \* \* mon root run-parts /etc/cron.weekly 
currently we don't have any other script that run weekly that gets affected by this scheduling.
